# -*- coding: utf-8 -*-
"""data-acquisition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OL-koqHWT-9Nrpr2Ckb-Hf_dJJZes0LP

# Specifying Libraries and Functions
"""

!pip install mediapipe==0.10.18 opencv-python==4.10.0.84 numpy==1.26.4 matplotlib==3.8.0 sounddevice==0.5.1

import cv2
import numpy as np
import os
import shutil
import time
import mediapipe as mp
from matplotlib import pyplot as plt

# ==========================================
# 1. SETUP AND HELPER FUNCTIONS
# ==========================================

mp_holistic = mp.solutions.holistic
mp_drawing = mp.solutions.drawing_utils

def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = model.process(image)
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    return image, results

def draw_styled_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2))
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2))
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2))

def extract_keypoints(results):
    # Slice [0:23] to keep only Face and Upper Body (excluding hips/legs)
    # Or specific indices if you want to be more precise
    if results.pose_landmarks:
        # Taking the first 25 landmarks (0-24) covers face + upper body up to hips
        pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark[:25]]).flatten()
    else:
        # 25 landmarks * 4 coordinates
        pose = np.zeros(25*4)

    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

    return np.concatenate([pose, lh, rh])

def cv2_imshow(image):
    # Convert BGR (OpenCV format) to RGB (Matplotlib format)
    if len(image.shape) == 3:
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    else:
        plt.imshow(image, cmap='gray')
    plt.axis('off') # Hide the x/y axis numbers
    plt.show()

def detect_hand_landmarks(image_path):
    with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
        # Load the image using OpenCV
        image = cv2.imread(image_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Make detections
        image, results = mediapipe_detection(image, holistic)

        # Draw landmarks to the frame
        draw_styled_landmarks(image,results)

        # Convert the image back to BGR for OpenCV
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

        # Display the image with hand landmarks
        cv2_imshow(image)


# Testing mediapipe
# Path to your own image file
image_path = '/kaggle/input/cv-frame/test.jpg'

# Call the function to detect hand landmarks
detect_hand_landmarks(image_path)

video_directory = r'//kaggle/input/sign-language-dataset/BIM Dataset V3'
train_dataset_path = '/kaggle/working/video_dataset'

MIN_SAMPLES = 50  # Gestures with fewer than 20 videos will be DROPPED
VALID_EXTENSIONS = ('.mp4', '.avi', '.mov', '.mkv')

# ==========================================
# 2. PRE-SCAN & DROPPING LOGIC
# ==========================================
print("--- Initial Class Distribution Check ---")
all_gesture_folders = sorted([d for d in os.listdir(video_directory)
                              if os.path.isdir(os.path.join(video_directory, d))])

valid_gestures = []
dropped_gestures = []

for ges in all_gesture_folders:
    path = os.path.join(video_directory, ges)
    # Only count actual video files
    video_files = [f for f in os.listdir(path) if f.lower().endswith(VALID_EXTENSIONS)]

    if len(video_files) >= MIN_SAMPLES:
        valid_gestures.append((ges, video_files))
    else:
        dropped_gestures.append(f"{ges} ({len(video_files)} samples)")

# 1. Total Original Gestures
print(f"Total Original Folders Found: {len(all_gesture_folders)}")
print(f"Original Gestures List:\n{all_gesture_folders}")
print("-" * 30)

# 2. Dropped Gestures Detail
print(f"DROPPED: {len(dropped_gestures)} gestures (SAMPLES < {MIN_SAMPLES})")
if dropped_gestures:
    for d in dropped_gestures:
        print(f"  {d}")
else:
    print("  (None)")
print("-" * 30)

# 3. Final Selection
# Extract just the names from our valid_gestures list of tuples
final_gesture_names = [g[0] for g in valid_gestures]

print(f"FINAL TOTAL: {len(final_gesture_names)} gestures kept.")
print(f"Final Gestures List:\n{final_gesture_names}")
print("="*50 + "\n")

# ==========================================
# 3. DATA ACQUISITION LOOP
# ==========================================

# Clean start
if os.path.exists(train_dataset_path):
    shutil.rmtree(train_dataset_path)
os.makedirs(train_dataset_path, exist_ok=True)

with mp.solutions.holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    for i, (ges, video_files) in enumerate(valid_gestures):
        gesture_save_path = os.path.join(train_dataset_path, ges)
        os.makedirs(gesture_save_path, exist_ok=True)

        total_videos = len(video_files)
        print(f"[{i+1}/{len(valid_gestures)}] Extracting: '{ges}'...")

        for j, vid in enumerate(video_files):
            print(f"    > Video {j+1}/{total_videos}: {vid[:25]}...", end='\r')

            video_path = os.path.join(video_directory, ges, vid)
            cap = cv2.VideoCapture(video_path)

            # Read Frames
            frames = []
            while True:
                ret, frame = cap.read()
                if not ret: break
                frames.append(frame)
            cap.release()

            # Internal Validation: Skip if video is empty/corrupt
            if len(frames) == 0:
                continue

            # Uniform Sampling (30 frames)
            frame_indices = np.linspace(0, len(frames) - 1, 30).astype(int)
            sequence_data = []

            for idx in frame_indices:
                _, results = mediapipe_detection(frames[idx], holistic)
                keypoints = extract_keypoints(results)
                sequence_data.append(keypoints)

            # Save .npy
            save_name = os.path.splitext(vid)[0] + '.npy'
            np.save(os.path.join(gesture_save_path, save_name), np.array(sequence_data))

        print(f"\n    Completed '{ges}'.")

print("\nLandmarks Dataset Creation Complete.")

import shutil
import os

# Define the source folder and the output zip name
source_folder = '/kaggle/working/video_dataset'
output_filename = '/kaggle/working/dataset' # Do not add .zip here, shutil does it automatically

print("Zipping files... this may take a moment.")
shutil.make_archive(output_filename, 'zip', source_folder)
print(f"Success! Created {output_filename}.zip")